# File empty by default.
# Replace contents of this file with custom configuration.

[BATTERY_CHARGING_CTL]
algo_type monitor
sampling 1000
sensor         skin-msm-therm
thresholds     40000   42000   43000    45000    46000     48000     49000    50000    52000    90000
thresholds_clr 38000   40000   42000    43000    45000     46000     48000    49000    50000    53000
actions        battery battery battery  battery  battery   battery   battery  battery  battery  battery
action_info    1       2       3        4        5         6         7        8        10       10

[Thermal_Broadcast_MONITOR]
algo_type       monitor
sampling        1000
sensor          cam-flash-therm
thresholds      60000    62000    67000
thresholds_clr  58000    60000    62000
actions         report   report   report
action_info     1        2        3

[SKIN_CPU_MONITOR]
algo_type        monitor
sampling         1000
sensor           skin-msm-therm
thresholds       43000                        45000                      47000                      49000                              51000                               53000
thresholds_clr   42000                        43000                      45000                      47000                              49000                               51000
actions          cpu-cluster0+cpu-cluster1    cpu-cluster0+cpu-cluster1  cpu-cluster0+cpu-cluster1  cpu-cluster0+cpu-cluster1+cdsp_sw  cpu-cluster0+cpu-cluster1+cdsp_sw   cpu-cluster0+cpu-cluster1+cdsp_sw
action_info      3187200+3648000              2496000+2668800            2227200+2438400            1996800+2227200+3                  1670400+1977600+4                   1440000+1632000+5


[SKIN_GPU_MONITOR]
algo_type      monitor
sampling       1000
sensor         skin-msm-therm
thresholds     40000         42000            44000          48000
thresholds_clr 38000         40000            42000          46000
actions        gpu           gpu              gpu            gpu
action_info    826000000     646000000        578000000      382000000

[virtual-sensor-0]
algo_type          virtual
trip_sensor        skin-msm-therm  xo-therm
trip_sensor_logic  &&
thresholds          50000    50000
thresholds_clr      45000    45000
sensors            skin-msm-therm  xo-therm
weights            9 1
sampling           1000

[virtual-sensor-4]
algo_type          virtual
trip_sensor        skin-msm-therm  xo-therm
trip_sensor_logic  &&
thresholds          42000    42000
thresholds_clr      37000    37000
sensors            skin-msm-therm  xo-therm
weights            9 1
sampling           1000

[virtual-sensor-6]
algo_type          virtual
trip_sensor        skin-msm-therm  xo-therm
trip_sensor_logic  &&
thresholds          41000    41000
thresholds_clr      37000    37000
sensors            skin-msm-therm  xo-therm
weights            9 1
sampling           1000

[CCC-MONITOR]
algo_type    monitor
sampling     1000
sensor virtual-sensor-0
thresholds      56000   58000   60000
thresholds_clr  54000   56000   58000
actions         report  report  report
action_info     1       2       3

[Charge_Broadcast_MONITOR]
algo_type       monitor
sampling        1000
sensor          virtual-sensor-4
thresholds      49000    52000
thresholds_clr  45000    49000
actions         report   report
action_info     1        2

[Camera_Broadcast_MONITOR]
algo_type       monitor
sampling        1000
sensor          virtual-sensor-6
thresholds      46000    50000
thresholds_clr  43000    46000
actions         report   report
action_info     1        2